server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql:///shangtouhua
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:com/shangtouhua/dao/mapper/*.xml
  type-aliases-package: com.shangtouhua.entity